/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.1.7-dev at Tue Nov 13 15:12:47 2012. */

#include "command.pb.h"

const pb_field_t SensorData_fields[5] = {
    {1, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_STRING),
    offsetof(SensorData, type), 0,
    pb_membersize(SensorData, type), 0, 0},

    {2, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_STRING),
    pb_delta_end(SensorData, description, type), 0,
    pb_membersize(SensorData, description), 0, 0},

    {3, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(SensorData, address, description), 0,
    pb_membersize(SensorData, address), 0, 0},

    {4, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(SensorData, value, address), 0,
    pb_membersize(SensorData, value), 0, 0},

    PB_LAST_FIELD
};

const pb_field_t DriveSignals_fields[4] = {
    {1, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    offsetof(DriveSignals, forward), 0,
    pb_membersize(DriveSignals, forward), 0, 0},

    {2, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(DriveSignals, enable, forward), 0,
    pb_membersize(DriveSignals, enable), 0, 0},

    {3, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_VARINT),
    pb_delta_end(DriveSignals, power, enable), 0,
    pb_membersize(DriveSignals, power), 0, 0},

    PB_LAST_FIELD
};

const pb_field_t Engines_fields[3] = {
    {1, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_SUBMESSAGE),
    offsetof(Engines, right), 0,
    pb_membersize(Engines, right), 0,
    &DriveSignals_fields},

    {2, (pb_type_t) ((int) PB_HTYPE_REQUIRED | (int) PB_LTYPE_SUBMESSAGE),
    pb_delta_end(Engines, left, right), 0,
    pb_membersize(Engines, left), 0,
    &DriveSignals_fields},

    PB_LAST_FIELD
};
