/* Automatically generated nanopb header */
/* Generated by nanopb-0.1.7-dev at Tue Nov 13 15:12:47 2012. */

#ifndef _PB_COMMAND_PB_H_
#define _PB_COMMAND_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _Protocol {
    char command[40];
    char adress[40];
    bool has_data;
    char data[40];
} Protocol;

/* Default values for struct fields */

/* Struct field encoding specification for nanopb */
extern const pb_field_t Protocol_fields[4];

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
