// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package protocolbufferjava;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string xCoor = 1;
    boolean hasXCoor();
    String getXCoor();
    
    // required string yCoor = 2;
    boolean hasYCoor();
    String getYCoor();
    
    // required string zCoor = 3;
    boolean hasZCoor();
    String getZCoor();
  }
  public static final class Protocol extends
      com.google.protobuf.GeneratedMessage
      implements ProtocolOrBuilder {
    // Use Protocol.newBuilder() to construct.
    private Protocol(Builder builder) {
      super(builder);
    }
    private Protocol(boolean noInit) {}
    
    private static final Protocol defaultInstance;
    public static Protocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public Protocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocolbufferjava.Test.internal_static_protocolbufferjava_Protocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocolbufferjava.Test.internal_static_protocolbufferjava_Protocol_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string xCoor = 1;
    public static final int XCOOR_FIELD_NUMBER = 1;
    private java.lang.Object xCoor_;
    public boolean hasXCoor() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getXCoor() {
      java.lang.Object ref = xCoor_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          xCoor_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getXCoorBytes() {
      java.lang.Object ref = xCoor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        xCoor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string yCoor = 2;
    public static final int YCOOR_FIELD_NUMBER = 2;
    private java.lang.Object yCoor_;
    public boolean hasYCoor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getYCoor() {
      java.lang.Object ref = yCoor_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          yCoor_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getYCoorBytes() {
      java.lang.Object ref = yCoor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        yCoor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string zCoor = 3;
    public static final int ZCOOR_FIELD_NUMBER = 3;
    private java.lang.Object zCoor_;
    public boolean hasZCoor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getZCoor() {
      java.lang.Object ref = zCoor_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          zCoor_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getZCoorBytes() {
      java.lang.Object ref = zCoor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        zCoor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      xCoor_ = "";
      yCoor_ = "";
      zCoor_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasXCoor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYCoor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZCoor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getXCoorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getYCoorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getZCoorBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getXCoorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getYCoorBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getZCoorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protocolbufferjava.Test.Protocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocolbufferjava.Test.Protocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocolbufferjava.Test.Protocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protocolbufferjava.Test.Protocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protocolbufferjava.Test.Protocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocolbufferjava.Test.Protocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protocolbufferjava.Test.Protocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocolbufferjava.Test.Protocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protocolbufferjava.Test.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protocolbufferjava.Test.Protocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocolbufferjava.Test.Protocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocolbufferjava.Test.ProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocolbufferjava.Test.internal_static_protocolbufferjava_Protocol_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocolbufferjava.Test.internal_static_protocolbufferjava_Protocol_fieldAccessorTable;
      }
      
      // Construct using protocolbufferjava.Test.Protocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        xCoor_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        yCoor_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        zCoor_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocolbufferjava.Test.Protocol.getDescriptor();
      }
      
      public protocolbufferjava.Test.Protocol getDefaultInstanceForType() {
        return protocolbufferjava.Test.Protocol.getDefaultInstance();
      }
      
      public protocolbufferjava.Test.Protocol build() {
        protocolbufferjava.Test.Protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protocolbufferjava.Test.Protocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protocolbufferjava.Test.Protocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protocolbufferjava.Test.Protocol buildPartial() {
        protocolbufferjava.Test.Protocol result = new protocolbufferjava.Test.Protocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.xCoor_ = xCoor_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.yCoor_ = yCoor_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.zCoor_ = zCoor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocolbufferjava.Test.Protocol) {
          return mergeFrom((protocolbufferjava.Test.Protocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protocolbufferjava.Test.Protocol other) {
        if (other == protocolbufferjava.Test.Protocol.getDefaultInstance()) return this;
        if (other.hasXCoor()) {
          setXCoor(other.getXCoor());
        }
        if (other.hasYCoor()) {
          setYCoor(other.getYCoor());
        }
        if (other.hasZCoor()) {
          setZCoor(other.getZCoor());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasXCoor()) {
          
          return false;
        }
        if (!hasYCoor()) {
          
          return false;
        }
        if (!hasZCoor()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              xCoor_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              yCoor_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              zCoor_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string xCoor = 1;
      private java.lang.Object xCoor_ = "";
      public boolean hasXCoor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getXCoor() {
        java.lang.Object ref = xCoor_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          xCoor_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setXCoor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        xCoor_ = value;
        onChanged();
        return this;
      }
      public Builder clearXCoor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        xCoor_ = getDefaultInstance().getXCoor();
        onChanged();
        return this;
      }
      void setXCoor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        xCoor_ = value;
        onChanged();
      }
      
      // required string yCoor = 2;
      private java.lang.Object yCoor_ = "";
      public boolean hasYCoor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getYCoor() {
        java.lang.Object ref = yCoor_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          yCoor_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setYCoor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        yCoor_ = value;
        onChanged();
        return this;
      }
      public Builder clearYCoor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        yCoor_ = getDefaultInstance().getYCoor();
        onChanged();
        return this;
      }
      void setYCoor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        yCoor_ = value;
        onChanged();
      }
      
      // required string zCoor = 3;
      private java.lang.Object zCoor_ = "";
      public boolean hasZCoor() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getZCoor() {
        java.lang.Object ref = zCoor_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          zCoor_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setZCoor(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        zCoor_ = value;
        onChanged();
        return this;
      }
      public Builder clearZCoor() {
        bitField0_ = (bitField0_ & ~0x00000004);
        zCoor_ = getDefaultInstance().getZCoor();
        onChanged();
        return this;
      }
      void setZCoor(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        zCoor_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:protocolbufferjava.Protocol)
    }
    
    static {
      defaultInstance = new Protocol(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protocolbufferjava.Protocol)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocolbufferjava_Protocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocolbufferjava_Protocol_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\022protocolbufferjava\"7\n\010Prot" +
      "ocol\022\r\n\005xCoor\030\001 \002(\t\022\r\n\005yCoor\030\002 \002(\t\022\r\n\005zC" +
      "oor\030\003 \002(\tB\024\n\022protocolbufferjava"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocolbufferjava_Protocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocolbufferjava_Protocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocolbufferjava_Protocol_descriptor,
              new java.lang.String[] { "XCoor", "YCoor", "ZCoor", },
              protocolbufferjava.Test.Protocol.class,
              protocolbufferjava.Test.Protocol.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
