/* Automatically generated nanopb header */
/* Generated by nanopb-0.1.7-dev at Tue Nov 13 15:12:47 2012. */

#ifndef _PB_COMMAND_PB_H_
#define _PB_COMMAND_PB_H_
#include <pb.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _DriveSignals {
    bool forward;
    bool enable;
    int32_t power;
} DriveSignals;

typedef struct _SensorData {
    char type[40];
    char description[40];
    int32_t address;
    int32_t value;
} SensorData;

typedef struct _Engines {
    DriveSignals right;
    DriveSignals left;
} Engines;

/* Default values for struct fields */

/* Struct field encoding specification for nanopb */
extern const pb_field_t SensorData_fields[5];
extern const pb_field_t DriveSignals_fields[4];
extern const pb_field_t Engines_fields[3];

/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(Engines, right) < 256 && pb_membersize(Engines, left) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT)
#endif

#if !defined(PB_FIELD_32BIT)
STATIC_ASSERT((pb_membersize(Engines, right) < 65536 && pb_membersize(Engines, left) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
