// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Command.proto

package on.hovercraft.android;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SensorDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string type = 1;
    boolean hasType();
    String getType();
    
    // required string description = 2;
    boolean hasDescription();
    String getDescription();
    
    // required uint32 address = 3;
    boolean hasAddress();
    int getAddress();
    
    // required uint32 value = 4;
    boolean hasValue();
    int getValue();
  }
  public static final class SensorData extends
      com.google.protobuf.GeneratedMessage
      implements SensorDataOrBuilder {
    // Use SensorData.newBuilder() to construct.
    private SensorData(Builder builder) {
      super(builder);
    }
    private SensorData(boolean noInit) {}
    
    private static final SensorData defaultInstance;
    public static SensorData getDefaultInstance() {
      return defaultInstance;
    }
    
    public SensorData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return on.hovercraft.android.Command.internal_static_on_hover_android_SensorData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return on.hovercraft.android.Command.internal_static_on_hover_android_SensorData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string description = 2;
    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private java.lang.Object description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          description_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 address = 3;
    public static final int ADDRESS_FIELD_NUMBER = 3;
    private int address_;
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getAddress() {
      return address_;
    }
    
    // required uint32 value = 4;
    public static final int VALUE_FIELD_NUMBER = 4;
    private int value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getValue() {
      return value_;
    }
    
    private void initFields() {
      type_ = "";
      description_ = "";
      address_ = 0;
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, address_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, value_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, address_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static on.hovercraft.android.Command.SensorData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static on.hovercraft.android.Command.SensorData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.SensorData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static on.hovercraft.android.Command.SensorData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.SensorData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static on.hovercraft.android.Command.SensorData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.SensorData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static on.hovercraft.android.Command.SensorData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static on.hovercraft.android.Command.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static on.hovercraft.android.Command.SensorData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(on.hovercraft.android.Command.SensorData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements on.hovercraft.android.Command.SensorDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return on.hovercraft.android.Command.internal_static_on_hover_android_SensorData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return on.hovercraft.android.Command.internal_static_on_hover_android_SensorData_fieldAccessorTable;
      }
      
      // Construct using on.hover.android.Command.SensorData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return on.hovercraft.android.Command.SensorData.getDescriptor();
      }
      
      public on.hovercraft.android.Command.SensorData getDefaultInstanceForType() {
        return on.hovercraft.android.Command.SensorData.getDefaultInstance();
      }
      
      public on.hovercraft.android.Command.SensorData build() {
        on.hovercraft.android.Command.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private on.hovercraft.android.Command.SensorData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        on.hovercraft.android.Command.SensorData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public on.hovercraft.android.Command.SensorData buildPartial() {
        on.hovercraft.android.Command.SensorData result = new on.hovercraft.android.Command.SensorData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof on.hovercraft.android.Command.SensorData) {
          return mergeFrom((on.hovercraft.android.Command.SensorData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(on.hovercraft.android.Command.SensorData other) {
        if (other == on.hovercraft.android.Command.SensorData.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              description_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              address_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              value_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string type = 1;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
      }
      
      // required string description = 2;
      private java.lang.Object description_ = "";
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescription(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      void setDescription(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        description_ = value;
        onChanged();
      }
      
      // required uint32 address = 3;
      private int address_ ;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getAddress() {
        return address_;
      }
      public Builder setAddress(int value) {
        bitField0_ |= 0x00000004;
        address_ = value;
        onChanged();
        return this;
      }
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000004);
        address_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 value = 4;
      private int value_ ;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getValue() {
        return value_;
      }
      public Builder setValue(int value) {
        bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:on.hover.android.SensorData)
    }
    
    static {
      defaultInstance = new SensorData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:on.hover.android.SensorData)
  }
  
  public interface DriveSignalsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required bool forward = 1;
    boolean hasForward();
    boolean getForward();
    
    // required bool enable = 2;
    boolean hasEnable();
    boolean getEnable();
    
    // required uint32 power = 3;
    boolean hasPower();
    int getPower();
  }
  public static final class DriveSignals extends
      com.google.protobuf.GeneratedMessage
      implements DriveSignalsOrBuilder {
    // Use DriveSignals.newBuilder() to construct.
    private DriveSignals(Builder builder) {
      super(builder);
    }
    private DriveSignals(boolean noInit) {}
    
    private static final DriveSignals defaultInstance;
    public static DriveSignals getDefaultInstance() {
      return defaultInstance;
    }
    
    public DriveSignals getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return on.hovercraft.android.Command.internal_static_on_hover_android_DriveSignals_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return on.hovercraft.android.Command.internal_static_on_hover_android_DriveSignals_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool forward = 1;
    public static final int FORWARD_FIELD_NUMBER = 1;
    private boolean forward_;
    public boolean hasForward() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getForward() {
      return forward_;
    }
    
    // required bool enable = 2;
    public static final int ENABLE_FIELD_NUMBER = 2;
    private boolean enable_;
    public boolean hasEnable() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getEnable() {
      return enable_;
    }
    
    // required uint32 power = 3;
    public static final int POWER_FIELD_NUMBER = 3;
    private int power_;
    public boolean hasPower() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPower() {
      return power_;
    }
    
    private void initFields() {
      forward_ = false;
      enable_ = false;
      power_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasForward()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnable()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPower()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, forward_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, enable_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, power_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, forward_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, enable_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, power_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static on.hovercraft.android.Command.DriveSignals parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static on.hovercraft.android.Command.DriveSignals parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.DriveSignals parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static on.hovercraft.android.Command.DriveSignals parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.DriveSignals parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static on.hovercraft.android.Command.DriveSignals parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.DriveSignals parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static on.hovercraft.android.Command.DriveSignals parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static on.hovercraft.android.Command.DriveSignals parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static on.hovercraft.android.Command.DriveSignals parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(on.hovercraft.android.Command.DriveSignals prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements on.hovercraft.android.Command.DriveSignalsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return on.hovercraft.android.Command.internal_static_on_hover_android_DriveSignals_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return on.hovercraft.android.Command.internal_static_on_hover_android_DriveSignals_fieldAccessorTable;
      }
      
      // Construct using on.hover.android.Command.DriveSignals.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        forward_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        enable_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        power_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return on.hovercraft.android.Command.DriveSignals.getDescriptor();
      }
      
      public on.hovercraft.android.Command.DriveSignals getDefaultInstanceForType() {
        return on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
      }
      
      public on.hovercraft.android.Command.DriveSignals build() {
        on.hovercraft.android.Command.DriveSignals result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private on.hovercraft.android.Command.DriveSignals buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        on.hovercraft.android.Command.DriveSignals result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public on.hovercraft.android.Command.DriveSignals buildPartial() {
        on.hovercraft.android.Command.DriveSignals result = new on.hovercraft.android.Command.DriveSignals(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.forward_ = forward_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.enable_ = enable_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.power_ = power_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof on.hovercraft.android.Command.DriveSignals) {
          return mergeFrom((on.hovercraft.android.Command.DriveSignals)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(on.hovercraft.android.Command.DriveSignals other) {
        if (other == on.hovercraft.android.Command.DriveSignals.getDefaultInstance()) return this;
        if (other.hasForward()) {
          setForward(other.getForward());
        }
        if (other.hasEnable()) {
          setEnable(other.getEnable());
        }
        if (other.hasPower()) {
          setPower(other.getPower());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasForward()) {
          
          return false;
        }
        if (!hasEnable()) {
          
          return false;
        }
        if (!hasPower()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              forward_ = input.readBool();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              enable_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              power_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool forward = 1;
      private boolean forward_ ;
      public boolean hasForward() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getForward() {
        return forward_;
      }
      public Builder setForward(boolean value) {
        bitField0_ |= 0x00000001;
        forward_ = value;
        onChanged();
        return this;
      }
      public Builder clearForward() {
        bitField0_ = (bitField0_ & ~0x00000001);
        forward_ = false;
        onChanged();
        return this;
      }
      
      // required bool enable = 2;
      private boolean enable_ ;
      public boolean hasEnable() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getEnable() {
        return enable_;
      }
      public Builder setEnable(boolean value) {
        bitField0_ |= 0x00000002;
        enable_ = value;
        onChanged();
        return this;
      }
      public Builder clearEnable() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enable_ = false;
        onChanged();
        return this;
      }
      
      // required uint32 power = 3;
      private int power_ ;
      public boolean hasPower() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPower() {
        return power_;
      }
      public Builder setPower(int value) {
        bitField0_ |= 0x00000004;
        power_ = value;
        onChanged();
        return this;
      }
      public Builder clearPower() {
        bitField0_ = (bitField0_ & ~0x00000004);
        power_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:on.hover.android.DriveSignals)
    }
    
    static {
      defaultInstance = new DriveSignals(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:on.hover.android.DriveSignals)
  }
  
  public interface EnginesOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .on.hover.android.DriveSignals right = 1;
    boolean hasRight();
    on.hovercraft.android.Command.DriveSignals getRight();
    on.hovercraft.android.Command.DriveSignalsOrBuilder getRightOrBuilder();
    
    // required .on.hover.android.DriveSignals left = 2;
    boolean hasLeft();
    on.hovercraft.android.Command.DriveSignals getLeft();
    on.hovercraft.android.Command.DriveSignalsOrBuilder getLeftOrBuilder();
  }
  public static final class Engines extends
      com.google.protobuf.GeneratedMessage
      implements EnginesOrBuilder {
    // Use Engines.newBuilder() to construct.
    private Engines(Builder builder) {
      super(builder);
    }
    private Engines(boolean noInit) {}
    
    private static final Engines defaultInstance;
    public static Engines getDefaultInstance() {
      return defaultInstance;
    }
    
    public Engines getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return on.hovercraft.android.Command.internal_static_on_hover_android_Engines_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return on.hovercraft.android.Command.internal_static_on_hover_android_Engines_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .on.hover.android.DriveSignals right = 1;
    public static final int RIGHT_FIELD_NUMBER = 1;
    private on.hovercraft.android.Command.DriveSignals right_;
    public boolean hasRight() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public on.hovercraft.android.Command.DriveSignals getRight() {
      return right_;
    }
    public on.hovercraft.android.Command.DriveSignalsOrBuilder getRightOrBuilder() {
      return right_;
    }
    
    // required .on.hover.android.DriveSignals left = 2;
    public static final int LEFT_FIELD_NUMBER = 2;
    private on.hovercraft.android.Command.DriveSignals left_;
    public boolean hasLeft() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public on.hovercraft.android.Command.DriveSignals getLeft() {
      return left_;
    }
    public on.hovercraft.android.Command.DriveSignalsOrBuilder getLeftOrBuilder() {
      return left_;
    }
    
    private void initFields() {
      right_ = on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
      left_ = on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLeft()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRight().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getLeft().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, right_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, left_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, right_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, left_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static on.hovercraft.android.Command.Engines parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static on.hovercraft.android.Command.Engines parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.Engines parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static on.hovercraft.android.Command.Engines parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.Engines parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static on.hovercraft.android.Command.Engines parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static on.hovercraft.android.Command.Engines parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static on.hovercraft.android.Command.Engines parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static on.hovercraft.android.Command.Engines parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static on.hovercraft.android.Command.Engines parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(on.hovercraft.android.Command.Engines prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements on.hovercraft.android.Command.EnginesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return on.hovercraft.android.Command.internal_static_on_hover_android_Engines_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return on.hovercraft.android.Command.internal_static_on_hover_android_Engines_fieldAccessorTable;
      }
      
      // Construct using on.hover.android.Command.Engines.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRightFieldBuilder();
          getLeftFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (rightBuilder_ == null) {
          right_ = on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
        } else {
          rightBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (leftBuilder_ == null) {
          left_ = on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
        } else {
          leftBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return on.hovercraft.android.Command.Engines.getDescriptor();
      }
      
      public on.hovercraft.android.Command.Engines getDefaultInstanceForType() {
        return on.hovercraft.android.Command.Engines.getDefaultInstance();
      }
      
      public on.hovercraft.android.Command.Engines build() {
        on.hovercraft.android.Command.Engines result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private on.hovercraft.android.Command.Engines buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        on.hovercraft.android.Command.Engines result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public on.hovercraft.android.Command.Engines buildPartial() {
        on.hovercraft.android.Command.Engines result = new on.hovercraft.android.Command.Engines(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (rightBuilder_ == null) {
          result.right_ = right_;
        } else {
          result.right_ = rightBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (leftBuilder_ == null) {
          result.left_ = left_;
        } else {
          result.left_ = leftBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof on.hovercraft.android.Command.Engines) {
          return mergeFrom((on.hovercraft.android.Command.Engines)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(on.hovercraft.android.Command.Engines other) {
        if (other == on.hovercraft.android.Command.Engines.getDefaultInstance()) return this;
        if (other.hasRight()) {
          mergeRight(other.getRight());
        }
        if (other.hasLeft()) {
          mergeLeft(other.getLeft());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRight()) {
          
          return false;
        }
        if (!hasLeft()) {
          
          return false;
        }
        if (!getRight().isInitialized()) {
          
          return false;
        }
        if (!getLeft().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              on.hovercraft.android.Command.DriveSignals.Builder subBuilder = on.hovercraft.android.Command.DriveSignals.newBuilder();
              if (hasRight()) {
                subBuilder.mergeFrom(getRight());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRight(subBuilder.buildPartial());
              break;
            }
            case 18: {
              on.hovercraft.android.Command.DriveSignals.Builder subBuilder = on.hovercraft.android.Command.DriveSignals.newBuilder();
              if (hasLeft()) {
                subBuilder.mergeFrom(getLeft());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLeft(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .on.hover.android.DriveSignals right = 1;
      private on.hovercraft.android.Command.DriveSignals right_ = on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          on.hovercraft.android.Command.DriveSignals, on.hovercraft.android.Command.DriveSignals.Builder, on.hovercraft.android.Command.DriveSignalsOrBuilder> rightBuilder_;
      public boolean hasRight() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public on.hovercraft.android.Command.DriveSignals getRight() {
        if (rightBuilder_ == null) {
          return right_;
        } else {
          return rightBuilder_.getMessage();
        }
      }
      public Builder setRight(on.hovercraft.android.Command.DriveSignals value) {
        if (rightBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          right_ = value;
          onChanged();
        } else {
          rightBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setRight(
          on.hovercraft.android.Command.DriveSignals.Builder builderForValue) {
        if (rightBuilder_ == null) {
          right_ = builderForValue.build();
          onChanged();
        } else {
          rightBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeRight(on.hovercraft.android.Command.DriveSignals value) {
        if (rightBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              right_ != on.hovercraft.android.Command.DriveSignals.getDefaultInstance()) {
            right_ =
              on.hovercraft.android.Command.DriveSignals.newBuilder(right_).mergeFrom(value).buildPartial();
          } else {
            right_ = value;
          }
          onChanged();
        } else {
          rightBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearRight() {
        if (rightBuilder_ == null) {
          right_ = on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
          onChanged();
        } else {
          rightBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public on.hovercraft.android.Command.DriveSignals.Builder getRightBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRightFieldBuilder().getBuilder();
      }
      public on.hovercraft.android.Command.DriveSignalsOrBuilder getRightOrBuilder() {
        if (rightBuilder_ != null) {
          return rightBuilder_.getMessageOrBuilder();
        } else {
          return right_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          on.hovercraft.android.Command.DriveSignals, on.hovercraft.android.Command.DriveSignals.Builder, on.hovercraft.android.Command.DriveSignalsOrBuilder> 
          getRightFieldBuilder() {
        if (rightBuilder_ == null) {
          rightBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              on.hovercraft.android.Command.DriveSignals, on.hovercraft.android.Command.DriveSignals.Builder, on.hovercraft.android.Command.DriveSignalsOrBuilder>(
                  right_,
                  getParentForChildren(),
                  isClean());
          right_ = null;
        }
        return rightBuilder_;
      }
      
      // required .on.hover.android.DriveSignals left = 2;
      private on.hovercraft.android.Command.DriveSignals left_ = on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          on.hovercraft.android.Command.DriveSignals, on.hovercraft.android.Command.DriveSignals.Builder, on.hovercraft.android.Command.DriveSignalsOrBuilder> leftBuilder_;
      public boolean hasLeft() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public on.hovercraft.android.Command.DriveSignals getLeft() {
        if (leftBuilder_ == null) {
          return left_;
        } else {
          return leftBuilder_.getMessage();
        }
      }
      public Builder setLeft(on.hovercraft.android.Command.DriveSignals value) {
        if (leftBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          left_ = value;
          onChanged();
        } else {
          leftBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setLeft(
          on.hovercraft.android.Command.DriveSignals.Builder builderForValue) {
        if (leftBuilder_ == null) {
          left_ = builderForValue.build();
          onChanged();
        } else {
          leftBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeLeft(on.hovercraft.android.Command.DriveSignals value) {
        if (leftBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              left_ != on.hovercraft.android.Command.DriveSignals.getDefaultInstance()) {
            left_ =
              on.hovercraft.android.Command.DriveSignals.newBuilder(left_).mergeFrom(value).buildPartial();
          } else {
            left_ = value;
          }
          onChanged();
        } else {
          leftBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearLeft() {
        if (leftBuilder_ == null) {
          left_ = on.hovercraft.android.Command.DriveSignals.getDefaultInstance();
          onChanged();
        } else {
          leftBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public on.hovercraft.android.Command.DriveSignals.Builder getLeftBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLeftFieldBuilder().getBuilder();
      }
      public on.hovercraft.android.Command.DriveSignalsOrBuilder getLeftOrBuilder() {
        if (leftBuilder_ != null) {
          return leftBuilder_.getMessageOrBuilder();
        } else {
          return left_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          on.hovercraft.android.Command.DriveSignals, on.hovercraft.android.Command.DriveSignals.Builder, on.hovercraft.android.Command.DriveSignalsOrBuilder> 
          getLeftFieldBuilder() {
        if (leftBuilder_ == null) {
          leftBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              on.hovercraft.android.Command.DriveSignals, on.hovercraft.android.Command.DriveSignals.Builder, on.hovercraft.android.Command.DriveSignalsOrBuilder>(
                  left_,
                  getParentForChildren(),
                  isClean());
          left_ = null;
        }
        return leftBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:on.hover.android.Engines)
    }
    
    static {
      defaultInstance = new Engines(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:on.hover.android.Engines)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_on_hover_android_SensorData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_on_hover_android_SensorData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_on_hover_android_DriveSignals_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_on_hover_android_DriveSignals_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_on_hover_android_Engines_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_on_hover_android_Engines_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCommand.proto\022\020on.hover.android\"O\n\nSen" +
      "sorData\022\014\n\004type\030\001 \002(\t\022\023\n\013description\030\002 \002" +
      "(\t\022\017\n\007address\030\003 \002(\r\022\r\n\005value\030\004 \002(\r\">\n\014Dr" +
      "iveSignals\022\017\n\007forward\030\001 \002(\010\022\016\n\006enable\030\002 " +
      "\002(\010\022\r\n\005power\030\003 \002(\r\"f\n\007Engines\022-\n\005right\030\001" +
      " \002(\0132\036.on.hover.android.DriveSignals\022,\n\004" +
      "left\030\002 \002(\0132\036.on.hover.android.DriveSigna" +
      "ls"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_on_hover_android_SensorData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_on_hover_android_SensorData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_on_hover_android_SensorData_descriptor,
              new java.lang.String[] { "Type", "Description", "Address", "Value", },
              on.hovercraft.android.Command.SensorData.class,
              on.hovercraft.android.Command.SensorData.Builder.class);
          internal_static_on_hover_android_DriveSignals_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_on_hover_android_DriveSignals_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_on_hover_android_DriveSignals_descriptor,
              new java.lang.String[] { "Forward", "Enable", "Power", },
              on.hovercraft.android.Command.DriveSignals.class,
              on.hovercraft.android.Command.DriveSignals.Builder.class);
          internal_static_on_hover_android_Engines_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_on_hover_android_Engines_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_on_hover_android_Engines_descriptor,
              new java.lang.String[] { "Right", "Left", },
              on.hovercraft.android.Command.Engines.class,
              on.hovercraft.android.Command.Engines.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
